name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: go build -tags nucular_gio -ldflags="-H windowsgui -X 'main.hide_helper=true'" -o rblxutils.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rblxutils-windows
        path: rblxutils.exe
